// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api

import (
	"context"
	"net/http"
	"reflect"
)



// LocationAPIRouter defines the required methods for binding the api requests to a responses for the LocationAPI
// The LocationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a LocationAPIServicer to perform the required actions, then write the service results to the http response.
type LocationAPIRouter interface { 
	AccessPointGetById(http.ResponseWriter, *http.Request)
	AccessPointsGET(http.ResponseWriter, *http.Request)
	AreaSubDELETE(http.ResponseWriter, *http.Request)
	AreaSubGET(http.ResponseWriter, *http.Request)
	AreaSubListGET(http.ResponseWriter, *http.Request)
	AreaSubPOST(http.ResponseWriter, *http.Request)
	AreaSubPUT(http.ResponseWriter, *http.Request)
	DistanceGET(http.ResponseWriter, *http.Request)
	DistanceSubDELETE(http.ResponseWriter, *http.Request)
	DistanceSubGET(http.ResponseWriter, *http.Request)
	DistanceSubListGET(http.ResponseWriter, *http.Request)
	DistanceSubPOST(http.ResponseWriter, *http.Request)
	DistanceSubPUT(http.ResponseWriter, *http.Request)
	UserSubDELETE(http.ResponseWriter, *http.Request)
	UserSubGET(http.ResponseWriter, *http.Request)
	UserSubListGET(http.ResponseWriter, *http.Request)
	UserSubPOST(http.ResponseWriter, *http.Request)
	UserSubPUT(http.ResponseWriter, *http.Request)
	UsersGET(http.ResponseWriter, *http.Request)
	ZoneGetById(http.ResponseWriter, *http.Request)
	ZoneSubDELETE(http.ResponseWriter, *http.Request)
	ZoneSubGET(http.ResponseWriter, *http.Request)
	ZoneSubListGET(http.ResponseWriter, *http.Request)
	ZoneSubPOST(http.ResponseWriter, *http.Request)
	ZoneSubPUT(http.ResponseWriter, *http.Request)
	ZonesGET(http.ResponseWriter, *http.Request)
}


// LocationAPIServicer defines the api actions for the LocationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LocationAPIServicer interface { 
	AccessPointGetById(context.Context, string, string) (ImplResponse, error)
	AccessPointsGET(context.Context, string, []string) (ImplResponse, error)
	AreaSubDELETE(context.Context, string) (ImplResponse, error)
	AreaSubGET(context.Context, string) (ImplResponse, error)
	AreaSubListGET(context.Context, string) (ImplResponse, error)
	AreaSubPOST(context.Context, AreaSubPostRequest) (ImplResponse, error)
	AreaSubPUT(context.Context, string, AreaNotificationPostRequest) (ImplResponse, error)
	DistanceGET(context.Context, []string, DistanceGetLocationParameter) (ImplResponse, error)
	DistanceSubDELETE(context.Context, string) (ImplResponse, error)
	DistanceSubGET(context.Context, string) (ImplResponse, error)
	DistanceSubListGET(context.Context) (ImplResponse, error)
	DistanceSubPOST(context.Context, DistanceSubPostRequest) (ImplResponse, error)
	DistanceSubPUT(context.Context, string, DistanceSubPostRequest) (ImplResponse, error)
	UserSubDELETE(context.Context, string) (ImplResponse, error)
	UserSubGET(context.Context, string) (ImplResponse, error)
	UserSubListGET(context.Context, string, string) (ImplResponse, error)
	UserSubPOST(context.Context, UserSubPostRequest) (ImplResponse, error)
	UserSubPUT(context.Context, string, UserSubPostRequest) (ImplResponse, error)
	UsersGET(context.Context, []string, []string, []string) (ImplResponse, error)
	ZoneGetById(context.Context, string) (ImplResponse, error)
	ZoneSubDELETE(context.Context, string) (ImplResponse, error)
	ZoneSubGET(context.Context, string) (ImplResponse, error)
	ZoneSubListGET(context.Context, string, string) (ImplResponse, error)
	ZoneSubPOST(context.Context, ZoneSubPostRequest) (ImplResponse, error)
	ZoneSubPUT(context.Context, string, ZoneSubPostRequest) (ImplResponse, error)
	ZonesGET(context.Context, []string) (ImplResponse, error)
}
