// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api

import (
	"context"
	"net/http"
	"errors"
	"reflect"
)

// LocationAPIService is a service that implements the logic for the LocationAPIServicer
// This service should implement the business logic for every endpoint for the LocationAPI API.
// Include any external packages or services that will be required by this service.
type LocationAPIService struct {
}

// NewLocationAPIService creates a default api service
func NewLocationAPIService() *LocationAPIService {
	return &LocationAPIService{}
}

// AccessPointGetById - Query information about a specific access point under a zone.
func (s *LocationAPIService) AccessPointGetById(ctx context.Context, zoneId string, accessPointId string) (ImplResponse, error) {
	// TODO - update AccessPointGetById with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccessPointGetById200Response{}) or use other options such as http.Ok ...
	// return Response(200, AccessPointGetById200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AccessPointGetById method not implemented")
}

// AccessPointsGET - Query information about a specific access point or a list of access points under a zone
func (s *LocationAPIService) AccessPointsGET(ctx context.Context, zoneId string, accessPointId []string) (ImplResponse, error) {
	// TODO - update AccessPointsGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccessPointsGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AccessPointsGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AccessPointsGET method not implemented")
}

// AreaSubDELETE - Cancel a subscription
func (s *LocationAPIService) AreaSubDELETE(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update AreaSubDELETE with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AreaSubDELETE method not implemented")
}

// AreaSubGET - Retrieve subscription information
func (s *LocationAPIService) AreaSubGET(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update AreaSubGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaSubGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AreaSubGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AreaSubGET method not implemented")
}

// AreaSubListGET - Retrieves information about the subscriptions for this requestor.
func (s *LocationAPIService) AreaSubListGET(ctx context.Context, subscriptionType string) (ImplResponse, error) {
	// TODO - update AreaSubListGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaSubListGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AreaSubListGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AreaSubListGET method not implemented")
}

// AreaSubPOST - Creates subscription to area notifications.
func (s *LocationAPIService) AreaSubPOST(ctx context.Context, areaSubPostRequest AreaSubPostRequest) (ImplResponse, error) {
	// TODO - update AreaSubPOST with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, AreaSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(201, AreaSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(415, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AreaSubPOST method not implemented")
}

// AreaSubPUT - Updates a subscription information
func (s *LocationAPIService) AreaSubPUT(ctx context.Context, subscriptionId string, areaNotificationPostRequest AreaNotificationPostRequest) (ImplResponse, error) {
	// TODO - update AreaSubPUT with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaNotificationPostRequest{}) or use other options such as http.Ok ...
	// return Response(200, AreaNotificationPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(412, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(412, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AreaSubPUT method not implemented")
}

// DistanceGET - Query information about distance from a user to a location or between two users
func (s *LocationAPIService) DistanceGET(ctx context.Context, address []string, location DistanceGetLocationParameter) (ImplResponse, error) {
	// TODO - update DistanceGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DistanceGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, DistanceGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceGET method not implemented")
}

// DistanceSubDELETE - Cancel a subscription
func (s *LocationAPIService) DistanceSubDELETE(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update DistanceSubDELETE with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceSubDELETE method not implemented")
}

// DistanceSubGET - Retrieve user distance subscription information
func (s *LocationAPIService) DistanceSubGET(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update DistanceSubGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DistanceSubGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, DistanceSubGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceSubGET method not implemented")
}

// DistanceSubListGET - Retrieves all active subscriptions to distance change notifications
func (s *LocationAPIService) DistanceSubListGET(ctx context.Context) (ImplResponse, error) {
	// TODO - update DistanceSubListGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaSubListGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AreaSubListGet200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceSubListGET method not implemented")
}

// DistanceSubPOST - Creates a subscription for distance change notification
func (s *LocationAPIService) DistanceSubPOST(ctx context.Context, distanceSubPostRequest DistanceSubPostRequest) (ImplResponse, error) {
	// TODO - update DistanceSubPOST with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, DistanceSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(201, DistanceSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(415, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceSubPOST method not implemented")
}

// DistanceSubPUT - Updates a user distance subscription information
func (s *LocationAPIService) DistanceSubPUT(ctx context.Context, subscriptionId string, distanceSubPostRequest DistanceSubPostRequest) (ImplResponse, error) {
	// TODO - update DistanceSubPUT with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DistanceSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(200, DistanceSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(412, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(412, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DistanceSubPUT method not implemented")
}

// UserSubDELETE - Cancel a subscription
func (s *LocationAPIService) UserSubDELETE(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update UserSubDELETE with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserSubDELETE method not implemented")
}

// UserSubGET - Retrieve subscription information
func (s *LocationAPIService) UserSubGET(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update UserSubGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UserSubGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, UserSubGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserSubGET method not implemented")
}

// UserSubListGET - Retrieves information about the subscriptions for the requestor
func (s *LocationAPIService) UserSubListGET(ctx context.Context, subscriptionType string, address string) (ImplResponse, error) {
	// TODO - update UserSubListGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaSubListGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AreaSubListGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserSubListGET method not implemented")
}

// UserSubPOST - Create subscription to UE location notifications.
func (s *LocationAPIService) UserSubPOST(ctx context.Context, userSubPostRequest UserSubPostRequest) (ImplResponse, error) {
	// TODO - update UserSubPOST with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, UserSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(201, UserSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserSubPOST method not implemented")
}

// UserSubPUT - Updates a subscription information
func (s *LocationAPIService) UserSubPUT(ctx context.Context, subscriptionId string, userSubPostRequest UserSubPostRequest) (ImplResponse, error) {
	// TODO - update UserSubPUT with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UserSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(200, UserSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(412, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(412, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserSubPUT method not implemented")
}

// UsersGET - Query location information about a specific UE or a group of Ues
func (s *LocationAPIService) UsersGET(ctx context.Context, zoneId []string, accessPointId []string, address []string) (ImplResponse, error) {
	// TODO - update UsersGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UsersGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, UsersGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersGET method not implemented")
}

// ZoneGetById - Query information about a specific zone
func (s *LocationAPIService) ZoneGetById(ctx context.Context, zoneId string) (ImplResponse, error) {
	// TODO - update ZoneGetById with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ZoneGetById200Response{}) or use other options such as http.Ok ...
	// return Response(200, ZoneGetById200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneGetById method not implemented")
}

// ZoneSubDELETE - Cancel a zone subscription
func (s *LocationAPIService) ZoneSubDELETE(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update ZoneSubDELETE with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneSubDELETE method not implemented")
}

// ZoneSubGET - Retrieve zone subscription information
func (s *LocationAPIService) ZoneSubGET(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update ZoneSubGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ZoneSubGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, ZoneSubGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneSubGET method not implemented")
}

// ZoneSubListGET - Retrieves all active subscriptions to zone notifications
func (s *LocationAPIService) ZoneSubListGET(ctx context.Context, subscriptionType string, zoneId string) (ImplResponse, error) {
	// TODO - update ZoneSubListGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AreaSubListGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, AreaSubListGet200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneSubListGET method not implemented")
}

// ZoneSubPOST - Creates a subscription to zone notifications
func (s *LocationAPIService) ZoneSubPOST(ctx context.Context, zoneSubPostRequest ZoneSubPostRequest) (ImplResponse, error) {
	// TODO - update ZoneSubPOST with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, ZoneSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(201, ZoneSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(415, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneSubPOST method not implemented")
}

// ZoneSubPUT - Updates a zone subscription information
func (s *LocationAPIService) ZoneSubPUT(ctx context.Context, subscriptionId string, zoneSubPostRequest ZoneSubPostRequest) (ImplResponse, error) {
	// TODO - update ZoneSubPUT with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ZoneSubPostRequest{}) or use other options such as http.Ok ...
	// return Response(200, ZoneSubPostRequest{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(412, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(412, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(422, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(422, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZoneSubPUT method not implemented")
}

// ZonesGET - Query the information about one or more specific zones or a list of zones.
func (s *LocationAPIService) ZonesGET(ctx context.Context, zoneId []string) (ImplResponse, error) {
	// TODO - update ZonesGET with the required logic for this service method.
	// Add api_location_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ZonesGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, ZonesGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(401, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(406, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(406, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ZonesGET method not implemented")
}
