// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type Point struct {

	// Location latitude, expressed in the range -90° to +90°.
	Latitude float32 `json:"latitude"`

	// Location longitude, expressed in the range -180° to +180°.
	Longitude float32 `json:"longitude"`
}

// AssertPointRequired checks if the required fields are not zero-ed
func AssertPointRequired(obj Point) error {
	elements := map[string]interface{}{
		"latitude": obj.Latitude,
		"longitude": obj.Longitude,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPointConstraints checks if the values respects the defined constraints
func AssertPointConstraints(obj Point) error {
	return nil
}
