// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type DistanceSubPostRequest struct {

	UserDistanceSubscription UserDistanceSubscription `json:"userDistanceSubscription,omitempty"`
}

// AssertDistanceSubPostRequestRequired checks if the required fields are not zero-ed
func AssertDistanceSubPostRequestRequired(obj DistanceSubPostRequest) error {
	if err := AssertUserDistanceSubscriptionRequired(obj.UserDistanceSubscription); err != nil {
		return err
	}
	return nil
}

// AssertDistanceSubPostRequestConstraints checks if the values respects the defined constraints
func AssertDistanceSubPostRequestConstraints(obj DistanceSubPostRequest) error {
	if err := AssertUserDistanceSubscriptionConstraints(obj.UserDistanceSubscription); err != nil {
		return err
	}
	return nil
}
