// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type AccessPointsGet200Response struct {

	AccessPointList AccessPointList `json:"accessPointList,omitempty"`
}

// AssertAccessPointsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertAccessPointsGet200ResponseRequired(obj AccessPointsGet200Response) error {
	if err := AssertAccessPointListRequired(obj.AccessPointList); err != nil {
		return err
	}
	return nil
}

// AssertAccessPointsGet200ResponseConstraints checks if the values respects the defined constraints
func AssertAccessPointsGet200ResponseConstraints(obj AccessPointsGet200Response) error {
	if err := AssertAccessPointListConstraints(obj.AccessPointList); err != nil {
		return err
	}
	return nil
}
