// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type AreaNotificationPostRequest struct {

	UserAreaNotification UserAreaNotification `json:"userAreaNotification,omitempty"`
}

// AssertAreaNotificationPostRequestRequired checks if the required fields are not zero-ed
func AssertAreaNotificationPostRequestRequired(obj AreaNotificationPostRequest) error {
	if err := AssertUserAreaNotificationRequired(obj.UserAreaNotification); err != nil {
		return err
	}
	return nil
}

// AssertAreaNotificationPostRequestConstraints checks if the values respects the defined constraints
func AssertAreaNotificationPostRequestConstraints(obj AreaNotificationPostRequest) error {
	if err := AssertUserAreaNotificationConstraints(obj.UserAreaNotification); err != nil {
		return err
	}
	return nil
}
