// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// TerminalDistance - A type containing information about the distance from a terminal to a location or between two terminals, in addition the accuracy and a timestamp of the information are provided.
type TerminalDistance struct {

	// Accuracy of the provided distance in meters
	Accuracy int32 `json:"accuracy,omitempty"`

	// Distance from terminal to a location or between two terminals specified in meters
	Distance int32 `json:"distance"`

	Timestamp TimeStamp `json:"timestamp,omitempty"`
}

// AssertTerminalDistanceRequired checks if the required fields are not zero-ed
func AssertTerminalDistanceRequired(obj TerminalDistance) error {
	elements := map[string]interface{}{
		"distance": obj.Distance,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTimeStampRequired(obj.Timestamp); err != nil {
		return err
	}
	return nil
}

// AssertTerminalDistanceConstraints checks if the values respects the defined constraints
func AssertTerminalDistanceConstraints(obj TerminalDistance) error {
	if err := AssertTimeStampConstraints(obj.Timestamp); err != nil {
		return err
	}
	return nil
}
