// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// ZoneList - A type containing a list of zones.
type ZoneList struct {

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Collection of the zone information list.
	Zone []ZoneInfo `json:"zone,omitempty"`
}

// AssertZoneListRequired checks if the required fields are not zero-ed
func AssertZoneListRequired(obj ZoneList) error {
	elements := map[string]interface{}{
		"resourceURL": obj.ResourceURL,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Zone {
		if err := AssertZoneInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertZoneListConstraints checks if the values respects the defined constraints
func AssertZoneListConstraints(obj ZoneList) error {
	for _, el := range obj.Zone {
		if err := AssertZoneInfoConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
