// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type DistanceNotificationPostRequest struct {

	UserDistanceNotification UserDistanceNotification `json:"userDistanceNotification,omitempty"`
}

// AssertDistanceNotificationPostRequestRequired checks if the required fields are not zero-ed
func AssertDistanceNotificationPostRequestRequired(obj DistanceNotificationPostRequest) error {
	if err := AssertUserDistanceNotificationRequired(obj.UserDistanceNotification); err != nil {
		return err
	}
	return nil
}

// AssertDistanceNotificationPostRequestConstraints checks if the values respects the defined constraints
func AssertDistanceNotificationPostRequestConstraints(obj DistanceNotificationPostRequest) error {
	if err := AssertUserDistanceNotificationConstraints(obj.UserDistanceNotification); err != nil {
		return err
	}
	return nil
}
