// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneLocationEventSubscription struct {

	Links Links `json:"_links,omitempty"`

	// List of the users to be monitored. If not present, all the users need to be monitored.
	AddressList []string `json:"addressList,omitempty"`

	// URI exposed by the client on which to receive notifications via HTTP. See note 1.
	CallbackReference string `json:"callbackReference,omitempty"`

	// A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server. See note 2.
	ClientCorrelator string `json:"clientCorrelator,omitempty"`

	ExpiryDeadline TimeStamp `json:"expiryDeadline,omitempty"`

	// List of user event values to generate notifications for. 
	LocationEventCriteria []LocationEventType `json:"locationEventCriteria,omitempty"`

	ReportingCtrl ReportingCtrl `json:"reportingCtrl,omitempty"`

	// Set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, as specified in ETSI GS MEC 009 [4], clause 6.12a.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	// Shall be set to \"ZoneLocationEventSubscription\".
	SubscriptionType string `json:"subscriptionType"`

	WebsockNotifConfig WebsockNotifConfig `json:"websockNotifConfig,omitempty"`

	// Identifier of zone (e.g. zone001) to monitor.
	ZoneId string `json:"zoneId"`
}

// AssertZoneLocationEventSubscriptionRequired checks if the required fields are not zero-ed
func AssertZoneLocationEventSubscriptionRequired(obj ZoneLocationEventSubscription) error {
	elements := map[string]interface{}{
		"subscriptionType": obj.SubscriptionType,
		"zoneId": obj.ZoneId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLinksRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertTimeStampRequired(obj.ExpiryDeadline); err != nil {
		return err
	}
	if err := AssertReportingCtrlRequired(obj.ReportingCtrl); err != nil {
		return err
	}
	if err := AssertWebsockNotifConfigRequired(obj.WebsockNotifConfig); err != nil {
		return err
	}
	return nil
}

// AssertZoneLocationEventSubscriptionConstraints checks if the values respects the defined constraints
func AssertZoneLocationEventSubscriptionConstraints(obj ZoneLocationEventSubscription) error {
	if err := AssertLinksConstraints(obj.Links); err != nil {
		return err
	}
	if err := AssertTimeStampConstraints(obj.ExpiryDeadline); err != nil {
		return err
	}
	if err := AssertReportingCtrlConstraints(obj.ReportingCtrl); err != nil {
		return err
	}
	if err := AssertWebsockNotifConfigConstraints(obj.WebsockNotifConfig); err != nil {
		return err
	}
	return nil
}
