// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type MapInfo struct {

	// Ancillary map information may be used to convert coordinates between different coordinate systems.
	AncillaryMapInfo map[string]interface{} `json:"ancillaryMapInfo,omitempty"`

	// Indicates the ID of the map. 
	MapId string `json:"mapId"`

	Origin Origin `json:"origin,omitempty"`
}

// AssertMapInfoRequired checks if the required fields are not zero-ed
func AssertMapInfoRequired(obj MapInfo) error {
	elements := map[string]interface{}{
		"mapId": obj.MapId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertOriginRequired(obj.Origin); err != nil {
		return err
	}
	return nil
}

// AssertMapInfoConstraints checks if the values respects the defined constraints
func AssertMapInfoConstraints(obj MapInfo) error {
	if err := AssertOriginConstraints(obj.Origin); err != nil {
		return err
	}
	return nil
}
