// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// AccessPointList - A type containing list of access points.
type AccessPointList struct {

	// Collection of the access point information list.
	AccessPoint []AccessPointInfo `json:"accessPoint,omitempty"`

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Identifier of zone
	ZoneId string `json:"zoneId"`
}

// AssertAccessPointListRequired checks if the required fields are not zero-ed
func AssertAccessPointListRequired(obj AccessPointList) error {
	elements := map[string]interface{}{
		"resourceURL": obj.ResourceURL,
		"zoneId": obj.ZoneId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.AccessPoint {
		if err := AssertAccessPointInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccessPointListConstraints checks if the values respects the defined constraints
func AssertAccessPointListConstraints(obj AccessPointList) error {
	for _, el := range obj.AccessPoint {
		if err := AssertAccessPointInfoConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
