// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type WebsockNotifConfig struct {

	// Set to true by the service consumer to indicate that Websocket delivery is requested.
	RequestWebsocketUri bool `json:"requestWebsocketUri,omitempty"`

	// Set by location server to indicate to the service consumer the Websocket URI to be used for delivering notifications.
	WebsocketUri string `json:"websocketUri,omitempty"`
}

// AssertWebsockNotifConfigRequired checks if the required fields are not zero-ed
func AssertWebsockNotifConfigRequired(obj WebsockNotifConfig) error {
	return nil
}

// AssertWebsockNotifConfigConstraints checks if the values respects the defined constraints
func AssertWebsockNotifConfigConstraints(obj WebsockNotifConfig) error {
	return nil
}
