// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneLocationEventNotification struct {

	Links Links `json:"_links"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address"`

	// Shall be set to \"ZoneLocationEventNotification\".
	NotificationType string `json:"notificationType"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	UserLocationEvent LocationEventType `json:"userLocationEvent"`

	// The identity of the zone. 
	ZoneId string `json:"zoneId"`
}

// AssertZoneLocationEventNotificationRequired checks if the required fields are not zero-ed
func AssertZoneLocationEventNotificationRequired(obj ZoneLocationEventNotification) error {
	elements := map[string]interface{}{
		"_links": obj.Links,
		"address": obj.Address,
		"notificationType": obj.NotificationType,
		"userLocationEvent": obj.UserLocationEvent,
		"zoneId": obj.ZoneId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLinksRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertTimeStampRequired(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}

// AssertZoneLocationEventNotificationConstraints checks if the values respects the defined constraints
func AssertZoneLocationEventNotificationConstraints(obj ZoneLocationEventNotification) error {
	if err := AssertLinksConstraints(obj.Links); err != nil {
		return err
	}
	if err := AssertTimeStampConstraints(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}
