// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneSubPostRequest struct {

	ZoneLocationEventSubscription ZoneLocationEventSubscription `json:"zoneLocationEventSubscription,omitempty"`

	ZoneStatusSubscription ZoneStatusSubscription `json:"zoneStatusSubscription,omitempty"`
}

// AssertZoneSubPostRequestRequired checks if the required fields are not zero-ed
func AssertZoneSubPostRequestRequired(obj ZoneSubPostRequest) error {
	if err := AssertZoneLocationEventSubscriptionRequired(obj.ZoneLocationEventSubscription); err != nil {
		return err
	}
	if err := AssertZoneStatusSubscriptionRequired(obj.ZoneStatusSubscription); err != nil {
		return err
	}
	return nil
}

// AssertZoneSubPostRequestConstraints checks if the values respects the defined constraints
func AssertZoneSubPostRequestConstraints(obj ZoneSubPostRequest) error {
	if err := AssertZoneLocationEventSubscriptionConstraints(obj.ZoneLocationEventSubscription); err != nil {
		return err
	}
	if err := AssertZoneStatusSubscriptionConstraints(obj.ZoneStatusSubscription); err != nil {
		return err
	}
	return nil
}
