// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type UserAreaNotification struct {

	Links Links `json:"_links"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address"`

	CivicInfo CivicAddress `json:"civicInfo,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Shall be set to \"UserAreaNotification\".
	NotificationType string `json:"notificationType"`

	RelativeLocationInfo RelativeLocationInfo `json:"relativeLocationInfo,omitempty"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	UserLocationEvent LocationEventType `json:"userLocationEvent"`
}

// AssertUserAreaNotificationRequired checks if the required fields are not zero-ed
func AssertUserAreaNotificationRequired(obj UserAreaNotification) error {
	elements := map[string]interface{}{
		"_links": obj.Links,
		"address": obj.Address,
		"notificationType": obj.NotificationType,
		"userLocationEvent": obj.UserLocationEvent,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLinksRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertCivicAddressRequired(obj.CivicInfo); err != nil {
		return err
	}
	if err := AssertLocationInfoRequired(obj.LocationInfo); err != nil {
		return err
	}
	if err := AssertRelativeLocationInfoRequired(obj.RelativeLocationInfo); err != nil {
		return err
	}
	if err := AssertTimeStampRequired(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}

// AssertUserAreaNotificationConstraints checks if the values respects the defined constraints
func AssertUserAreaNotificationConstraints(obj UserAreaNotification) error {
	if err := AssertLinksConstraints(obj.Links); err != nil {
		return err
	}
	if err := AssertCivicAddressConstraints(obj.CivicInfo); err != nil {
		return err
	}
	if err := AssertLocationInfoConstraints(obj.LocationInfo); err != nil {
		return err
	}
	if err := AssertRelativeLocationInfoConstraints(obj.RelativeLocationInfo); err != nil {
		return err
	}
	if err := AssertTimeStampConstraints(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}
