// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// Origin - Indicates the location of the map origin in the local Cartesian coordinate system.
type Origin struct {

	// Location altitude relative to the WGS84 ellipsoid surface.
	Altitude float32 `json:"altitude,omitempty"`

	// Location latitude, expressed in the range -90° to +90°.
	Latitude float32 `json:"latitude"`

	// Location longitude, expressed in the range -180° to +180°.
	Longitude float32 `json:"longitude"`
}

// AssertOriginRequired checks if the required fields are not zero-ed
func AssertOriginRequired(obj Origin) error {
	elements := map[string]interface{}{
		"latitude": obj.Latitude,
		"longitude": obj.Longitude,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOriginConstraints checks if the values respects the defined constraints
func AssertOriginConstraints(obj Origin) error {
	return nil
}
