// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type DistanceGet200Response struct {

	TerminalDistance TerminalDistance `json:"terminalDistance,omitempty"`
}

// AssertDistanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertDistanceGet200ResponseRequired(obj DistanceGet200Response) error {
	if err := AssertTerminalDistanceRequired(obj.TerminalDistance); err != nil {
		return err
	}
	return nil
}

// AssertDistanceGet200ResponseConstraints checks if the values respects the defined constraints
func AssertDistanceGet200ResponseConstraints(obj DistanceGet200Response) error {
	if err := AssertTerminalDistanceConstraints(obj.TerminalDistance); err != nil {
		return err
	}
	return nil
}
