// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// AccessPointInfo - A type containing access point information.
type AccessPointInfo struct {

	// Identifier of access point.
	AccessPointId string `json:"accessPointId"`

	ConnectionType ConnectionType `json:"connectionType"`

	// Interest realm of access point.
	InterestRealm string `json:"interestRealm,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Number of users currently on the access point.
	NumberOfUsers int32 `json:"numberOfUsers"`

	OperationStatus OperationStatus `json:"operationStatus"`

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Time zone of access point.
	Timezone string `json:"timezone,omitempty"`
}

// AssertAccessPointInfoRequired checks if the required fields are not zero-ed
func AssertAccessPointInfoRequired(obj AccessPointInfo) error {
	elements := map[string]interface{}{
		"accessPointId": obj.AccessPointId,
		"connectionType": obj.ConnectionType,
		"numberOfUsers": obj.NumberOfUsers,
		"operationStatus": obj.OperationStatus,
		"resourceURL": obj.ResourceURL,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLocationInfoRequired(obj.LocationInfo); err != nil {
		return err
	}
	return nil
}

// AssertAccessPointInfoConstraints checks if the values respects the defined constraints
func AssertAccessPointInfoConstraints(obj AccessPointInfo) error {
	if err := AssertLocationInfoConstraints(obj.LocationInfo); err != nil {
		return err
	}
	return nil
}
