// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api


import (
	"fmt"
)


// DistanceCriteria : An enumeration, defining the distance criteria between devices.
type DistanceCriteria string

// List of DistanceCriteria
const (
	ALL_WITHIN_DISTANCE DistanceCriteria = "AllWithinDistance"
	ANY_WITHIN_DISTANCE DistanceCriteria = "AnyWithinDistance"
	ALL_BEYOND_DISTANCE DistanceCriteria = "AllBeyondDistance"
	ANY_BEYOND_DISTANCE DistanceCriteria = "AnyBeyondDistance"
)

// AllowedDistanceCriteriaEnumValues is all the allowed values of DistanceCriteria enum
var AllowedDistanceCriteriaEnumValues = []DistanceCriteria{
	"AllWithinDistance",
	"AnyWithinDistance",
	"AllBeyondDistance",
	"AnyBeyondDistance",
}

// validDistanceCriteriaEnumValue provides a map of DistanceCriterias for fast verification of use input
var validDistanceCriteriaEnumValues = map[DistanceCriteria]struct{}{
	"AllWithinDistance": {},
	"AnyWithinDistance": {},
	"AllBeyondDistance": {},
	"AnyBeyondDistance": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DistanceCriteria) IsValid() bool {
	_, ok := validDistanceCriteriaEnumValues[v]
	return ok
}

// NewDistanceCriteriaFromValue returns a pointer to a valid DistanceCriteria
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDistanceCriteriaFromValue(v string) (DistanceCriteria, error) {
	ev := DistanceCriteria(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for DistanceCriteria: valid values are %v", v, AllowedDistanceCriteriaEnumValues)
}



// AssertDistanceCriteriaRequired checks if the required fields are not zero-ed
func AssertDistanceCriteriaRequired(obj DistanceCriteria) error {
	return nil
}

// AssertDistanceCriteriaConstraints checks if the values respects the defined constraints
func AssertDistanceCriteriaConstraints(obj DistanceCriteria) error {
	return nil
}
