// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type UserNotificationPostRequest struct {

	UserLocationEventNotification UserLocationEventNotification `json:"userLocationEventNotification,omitempty"`

	UserLocationPeriodicNotification UserLocationPeriodicNotification `json:"userLocationPeriodicNotification,omitempty"`
}

// AssertUserNotificationPostRequestRequired checks if the required fields are not zero-ed
func AssertUserNotificationPostRequestRequired(obj UserNotificationPostRequest) error {
	if err := AssertUserLocationEventNotificationRequired(obj.UserLocationEventNotification); err != nil {
		return err
	}
	if err := AssertUserLocationPeriodicNotificationRequired(obj.UserLocationPeriodicNotification); err != nil {
		return err
	}
	return nil
}

// AssertUserNotificationPostRequestConstraints checks if the values respects the defined constraints
func AssertUserNotificationPostRequestConstraints(obj UserNotificationPostRequest) error {
	if err := AssertUserLocationEventNotificationConstraints(obj.UserLocationEventNotification); err != nil {
		return err
	}
	if err := AssertUserLocationPeriodicNotificationConstraints(obj.UserLocationPeriodicNotification); err != nil {
		return err
	}
	return nil
}
