// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// ServiceError - Used to indicate a notification termination or cancellation.
type ServiceError struct {

	// Message identifier, either with prefix SVC or with prefix POL
	MessageId string `json:"messageId"`

	// Message text, with replacement variables marked with %n, where n is an index into the list of <variables> elements, starting at 1
	Text string `json:"text"`

	// Variables to substitute into text string
	Variables []string `json:"variables,omitempty"`
}

// AssertServiceErrorRequired checks if the required fields are not zero-ed
func AssertServiceErrorRequired(obj ServiceError) error {
	elements := map[string]interface{}{
		"messageId": obj.MessageId,
		"text": obj.Text,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertServiceErrorConstraints checks if the values respects the defined constraints
func AssertServiceErrorConstraints(obj ServiceError) error {
	return nil
}
