// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneSubGet200Response struct {

	ZoneLocationEventSubscription ZoneLocationEventSubscription `json:"zoneLocationEventSubscription"`

	ZoneStatusSubscription ZoneStatusSubscription `json:"zoneStatusSubscription"`
}

// AssertZoneSubGet200ResponseRequired checks if the required fields are not zero-ed
func AssertZoneSubGet200ResponseRequired(obj ZoneSubGet200Response) error {
	elements := map[string]interface{}{
		"zoneLocationEventSubscription": obj.ZoneLocationEventSubscription,
		"zoneStatusSubscription": obj.ZoneStatusSubscription,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertZoneLocationEventSubscriptionRequired(obj.ZoneLocationEventSubscription); err != nil {
		return err
	}
	if err := AssertZoneStatusSubscriptionRequired(obj.ZoneStatusSubscription); err != nil {
		return err
	}
	return nil
}

// AssertZoneSubGet200ResponseConstraints checks if the values respects the defined constraints
func AssertZoneSubGet200ResponseConstraints(obj ZoneSubGet200Response) error {
	if err := AssertZoneLocationEventSubscriptionConstraints(obj.ZoneLocationEventSubscription); err != nil {
		return err
	}
	if err := AssertZoneStatusSubscriptionConstraints(obj.ZoneStatusSubscription); err != nil {
		return err
	}
	return nil
}
