// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZonesGet200Response struct {

	ZoneList ZoneList `json:"zoneList,omitempty"`
}

// AssertZonesGet200ResponseRequired checks if the required fields are not zero-ed
func AssertZonesGet200ResponseRequired(obj ZonesGet200Response) error {
	if err := AssertZoneListRequired(obj.ZoneList); err != nil {
		return err
	}
	return nil
}

// AssertZonesGet200ResponseConstraints checks if the values respects the defined constraints
func AssertZonesGet200ResponseConstraints(obj ZonesGet200Response) error {
	if err := AssertZoneListConstraints(obj.ZoneList); err != nil {
		return err
	}
	return nil
}
