// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type TimeStamp struct {

	// The nanoseconds part of the time. Time is defined as Unix-time since January 1, 1970, 00:00:00 UTC.
	NanoSeconds int32 `json:"nanoSeconds"`

	// The seconds part of the time. Time is defined as Unix-time since January 1, 1970, 00:00:00 UTC.
	Seconds int32 `json:"seconds"`
}

// AssertTimeStampRequired checks if the required fields are not zero-ed
func AssertTimeStampRequired(obj TimeStamp) error {
	elements := map[string]interface{}{
		"nanoSeconds": obj.NanoSeconds,
		"seconds": obj.Seconds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTimeStampConstraints checks if the values respects the defined constraints
func AssertTimeStampConstraints(obj TimeStamp) error {
	return nil
}
