// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneNotificationPostRequest struct {

	ZoneLocationEventNotification ZoneLocationEventNotification `json:"zoneLocationEventNotification,omitempty"`

	ZoneStatusNotification ZoneStatusNotification `json:"zoneStatusNotification,omitempty"`
}

// AssertZoneNotificationPostRequestRequired checks if the required fields are not zero-ed
func AssertZoneNotificationPostRequestRequired(obj ZoneNotificationPostRequest) error {
	if err := AssertZoneLocationEventNotificationRequired(obj.ZoneLocationEventNotification); err != nil {
		return err
	}
	if err := AssertZoneStatusNotificationRequired(obj.ZoneStatusNotification); err != nil {
		return err
	}
	return nil
}

// AssertZoneNotificationPostRequestConstraints checks if the values respects the defined constraints
func AssertZoneNotificationPostRequestConstraints(obj ZoneNotificationPostRequest) error {
	if err := AssertZoneLocationEventNotificationConstraints(obj.ZoneLocationEventNotification); err != nil {
		return err
	}
	if err := AssertZoneStatusNotificationConstraints(obj.ZoneStatusNotification); err != nil {
		return err
	}
	return nil
}
