// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type DistanceGetLocationParameter struct {

	// Location latitude, expressed in the range -90° to +90°.
	Latitude float32 `json:"latitude,omitempty"`

	// Location longitude, expressed in the range -180° to +180°.
	Longitude float32 `json:"longitude,omitempty"`
}

// AssertDistanceGetLocationParameterRequired checks if the required fields are not zero-ed
func AssertDistanceGetLocationParameterRequired(obj DistanceGetLocationParameter) error {
	return nil
}

// AssertDistanceGetLocationParameterConstraints checks if the values respects the defined constraints
func AssertDistanceGetLocationParameterConstraints(obj DistanceGetLocationParameter) error {
	return nil
}
