// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type UserDistanceNotification struct {

	Links Links `json:"_links"`

	DistanceEvent DistanceCriteria `json:"distanceEvent"`

	MonitoredUsers UserList `json:"monitoredUsers"`

	// Shall be set to \"UserDistanceNotification\".
	NotificationType string `json:"notificationType"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`
}

// AssertUserDistanceNotificationRequired checks if the required fields are not zero-ed
func AssertUserDistanceNotificationRequired(obj UserDistanceNotification) error {
	elements := map[string]interface{}{
		"_links": obj.Links,
		"distanceEvent": obj.DistanceEvent,
		"monitoredUsers": obj.MonitoredUsers,
		"notificationType": obj.NotificationType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLinksRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertUserListRequired(obj.MonitoredUsers); err != nil {
		return err
	}
	if err := AssertTimeStampRequired(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}

// AssertUserDistanceNotificationConstraints checks if the values respects the defined constraints
func AssertUserDistanceNotificationConstraints(obj UserDistanceNotification) error {
	if err := AssertLinksConstraints(obj.Links); err != nil {
		return err
	}
	if err := AssertUserListConstraints(obj.MonitoredUsers); err != nil {
		return err
	}
	if err := AssertTimeStampConstraints(obj.TimeStamp); err != nil {
		return err
	}
	return nil
}
