// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




type ZoneGetById200Response struct {

	ZoneInfo ZoneInfo `json:"zoneInfo,omitempty"`
}

// AssertZoneGetById200ResponseRequired checks if the required fields are not zero-ed
func AssertZoneGetById200ResponseRequired(obj ZoneGetById200Response) error {
	if err := AssertZoneInfoRequired(obj.ZoneInfo); err != nil {
		return err
	}
	return nil
}

// AssertZoneGetById200ResponseConstraints checks if the values respects the defined constraints
func AssertZoneGetById200ResponseConstraints(obj ZoneGetById200Response) error {
	if err := AssertZoneInfoConstraints(obj.ZoneInfo); err != nil {
		return err
	}
	return nil
}
