// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// UserList - A type containing list of users.
type UserList struct {

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Collection of the zone information list.
	User []UserInfo `json:"user,omitempty"`
}

// AssertUserListRequired checks if the required fields are not zero-ed
func AssertUserListRequired(obj UserList) error {
	elements := map[string]interface{}{
		"resourceURL": obj.ResourceURL,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.User {
		if err := AssertUserInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertUserListConstraints checks if the values respects the defined constraints
func AssertUserListConstraints(obj UserList) error {
	for _, el := range obj.User {
		if err := AssertUserInfoConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
