// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package location-api




// ZoneInfo - A type containing zone information.
type ZoneInfo struct {

	// The number of access points within the zone
	NumberOfAccessPoints int32 `json:"numberOfAccessPoints"`

	// Number of inoperable access points within the zone.
	NumberOfUnserviceableAccessPoints int32 `json:"numberOfUnserviceableAccessPoints"`

	// The number of users currently on the access point.
	NumberOfUsers int32 `json:"numberOfUsers"`

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Identifier of zone
	ZoneId string `json:"zoneId"`
}

// AssertZoneInfoRequired checks if the required fields are not zero-ed
func AssertZoneInfoRequired(obj ZoneInfo) error {
	elements := map[string]interface{}{
		"numberOfAccessPoints": obj.NumberOfAccessPoints,
		"numberOfUnserviceableAccessPoints": obj.NumberOfUnserviceableAccessPoints,
		"numberOfUsers": obj.NumberOfUsers,
		"resourceURL": obj.ResourceURL,
		"zoneId": obj.ZoneId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertZoneInfoConstraints checks if the values respects the defined constraints
func AssertZoneInfoConstraints(obj ZoneInfo) error {
	return nil
}
