// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 */

package main

import (
	"log"
	"net/http"

	location-api "github.com/izacarias/location-api/go"
)

func main() {
	log.Printf("Server started")

	LocationAPIService := location-api.NewLocationAPIService()
	LocationAPIController := location-api.NewLocationAPIController(LocationAPIService)

	router := location-api.NewRouter(LocationAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
