/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// Velocity - Structure with attributes relating to the target entity’s velocity, as defined in [14].
type Velocity struct {

	// Bearing, expressed in the range 0° to 360°, as defined in [14].
	Bearing int32 `json:"bearing"`

	// Horizontal speed, expressed in km/h and defined in [14].
	HorizontalSpeed int32 `json:"horizontalSpeed"`

	// Horizontal uncertainty, as defined in [14]. Present only if \"velocityType\" equals 3 or 4.
	Uncertainty int32 `json:"uncertainty,omitempty"`

	// Velocity information, as detailed in [14], associated with the reported location coordinate: 1 = Horizontal 2 = Horizontal_Vertical 3 = Horizontal_Uncert 4 = Horizontal_Vertical_Uncert
	VelocityType int32 `json:"velocityType"`

	// Vertical speed, expressed in km/h and defined in [14]. Present only if \"velocityType\" equals 2 or 4.
	VerticalSpeed int32 `json:"verticalSpeed,omitempty"`

	// Vertical uncertainty, as defined in [14]. Present only if \"velocityType\" equals 4.
	VerticalUncertainty int32 `json:"verticalUncertainty,omitempty"`
}
