/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type Point struct {

	// Location latitude, expressed in the range -90° to +90°.
	Latitude float32 `json:"latitude"`

	// Location longitude, expressed in the range -180° to +180°.
	Longitude float32 `json:"longitude"`
}
