/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserEventPara struct {

	// One or more access points forming a monitoring area that could be any shape. See note 1.
	AccessPointList []string `json:"accessPointList,omitempty"`

	OccurrenceInfo OccurrenceInfo `json:"occurrenceInfo,omitempty"`

	// This IE shall be set to true if a location estimate is required for each event report.
	ReportingLocationReq bool `json:"reportingLocationReq,omitempty"`

	// Identifier of zone (e.g. zone001) to monitor. See note 1.
	ZoneId string `json:"zoneId,omitempty"`
}
