/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api
// OccurrenceInfo : The enumeration OccurrenceInfo indicates whether event reporting is one time.
type OccurrenceInfo string

// List of OccurrenceInfo
const (
	ONE_TIME_EVENT OccurrenceInfo = "ONE_TIME_EVENT"
	MULTIPLE_TIME_EVENT OccurrenceInfo = "MULTIPLE_TIME_EVENT"
)
