/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type TimeStamp struct {

	// The nanoseconds part of the time. Time is defined as Unix-time since January 1, 1970, 00:00:00 UTC.
	NanoSeconds int32 `json:"nanoSeconds"`

	// The seconds part of the time. Time is defined as Unix-time since January 1, 1970, 00:00:00 UTC.
	Seconds int32 `json:"seconds"`
}
