/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserLocationPeriodicNotification struct {

	Links Links `json:"_links"`

	// The identity of the access point that the user is currently within.  See note 2.
	AccessPointId string `json:"accessPointId,omitempty"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address,omitempty"`

	CivicInfo CivicAddress `json:"civicInfo,omitempty"`

	// Shall be set to true if it is a final notification.
	IsFinalNotification bool `json:"isFinalNotification,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Shall be set to \"UserLocationPeriodicNotification\".
	NotificationType string `json:"notificationType"`

	RelativeLocationInfo RelativeLocationInfo `json:"relativeLocationInfo,omitempty"`

	Result NotificationResult `json:"result"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	// The identity of the zone that the user is currently within.  See note 2.
	ZoneId string `json:"zoneId,omitempty"`
}
