/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserLocationEventNotification struct {

	Links Links `json:"_links"`

	// The identity of the access point. For the events of \"ENTERING_AREA_EVENT\", it indicates the access point that the user is currently within.  For the event of \"LEAVING_AREA_EVENT\", it indicates the access point that the user used to be within. See note 2.
	AccessPointId string `json:"accessPointId,omitempty"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address,omitempty"`

	CivicInfo CivicAddress `json:"civicInfo,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Shall be set to \"UserLocationEventNotification\".
	NotificationType string `json:"notificationType"`

	RelativeLocationInfo RelativeLocationInfo `json:"relativeLocationInfo,omitempty"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	UserLocationEvent LocationEventType `json:"userLocationEvent"`

	// The identity of the zone.  For the events of \"ENTERING_AREA_EVENT\", it is the zone that the user is currently within.  For the event of \"LEAVING_AREA_EVENT\", it is the zone that the user used to be within. See note 2.
	ZoneId string `json:"zoneId,omitempty"`
}
