/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type ProblemDetails struct {

	// A human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail,omitempty"`

	// A URI reference that identifies the specific occurrence of the problem
	Instance string `json:"instance,omitempty"`

	// The HTTP status code for this occurrence of the problem
	Status int32 `json:"status,omitempty"`

	// A short, human-readable summary of the problem type
	Title string `json:"title,omitempty"`

	// A URI reference according to IETF RFC 3986 that identifies the problem type
	Type string `json:"type,omitempty"`
}
