/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api
// DistanceCriteria : An enumeration, defining the distance criteria between devices.
type DistanceCriteria string

// List of DistanceCriteria
const (
	ALL_WITHIN_DISTANCE DistanceCriteria = "AllWithinDistance"
	ANY_WITHIN_DISTANCE DistanceCriteria = "AnyWithinDistance"
	ALL_BEYOND_DISTANCE DistanceCriteria = "AllBeyondDistance"
	ANY_BEYOND_DISTANCE DistanceCriteria = "AnyBeyondDistance"
)
