/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type ZoneLocationEventSubscription struct {

	Links Links `json:"_links,omitempty"`

	// List of the users to be monitored. If not present, all the users need to be monitored.
	AddressList []string `json:"addressList,omitempty"`

	// URI exposed by the client on which to receive notifications via HTTP. See note 1.
	CallbackReference string `json:"callbackReference,omitempty"`

	// A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server. See note 2.
	ClientCorrelator string `json:"clientCorrelator,omitempty"`

	ExpiryDeadline TimeStamp `json:"expiryDeadline,omitempty"`

	// List of user event values to generate notifications for. 
	LocationEventCriteria []LocationEventType `json:"locationEventCriteria,omitempty"`

	ReportingCtrl ReportingCtrl `json:"reportingCtrl,omitempty"`

	// Set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, as specified in ETSI GS MEC 009 [4], clause 6.12a.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	// Shall be set to \"ZoneLocationEventSubscription\".
	SubscriptionType string `json:"subscriptionType"`

	WebsockNotifConfig WebsockNotifConfig `json:"websockNotifConfig,omitempty"`

	// Identifier of zone (e.g. zone001) to monitor.
	ZoneId string `json:"zoneId"`
}
