/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserDistanceSubscription struct {

	Links Links `json:"_links,omitempty"`

	// URI exposed by the client on which to receive notifications via HTTP. See note 1.
	CallbackReference string `json:"callbackReference,omitempty"`

	CheckImmediate bool `json:"checkImmediate"`

	// A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server. See note 2.
	ClientCorrelator string `json:"clientCorrelator,omitempty"`

	Criteria DistanceCriteria `json:"criteria"`

	// Distance between users that shall be monitored. The unit is meter.
	Distance float32 `json:"distance"`

	ExpiryDeadline TimeStamp `json:"expiryDeadline,omitempty"`

	// Contains addresses of users to monitor (e.g., ‘sip’ URI, ‘tel’ URI, ‘acr’ URI). Reference to a group could be provided here if supported by implementation. If the ReferenceAddress is specified, then the distance between each monitored user and reference user(s) will be monitored. If the ReferenceAddress is not present, then the distance between each pair of the monitored users will be monitored. Note that in that case there shall be at least two addresses specified here.
	MonitoredAddress []string `json:"monitoredAddress"`

	// If specified, indicates address of each user that will be used as reference users from which the distances towards monitored users indicated in the Addresses will be monitored (e.g., ‘sip’ URI, ‘tel’ URI, ‘acr’ URI). Reference to a group could be provided here if supported by implementation.
	ReferenceAddress []string `json:"referenceAddress,omitempty"`

	ReportingCtrl ReportingCtrl `json:"reportingCtrl,omitempty"`

	// Set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, as specified in ETSI GS MEC 009 [4], clause 6.12a.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	// Shall be set to \"UserDistanceSubscription\".
	SubscriptionType string `json:"subscriptionType"`

	// Number of meters of acceptable error in tracking distance.
	TrackingAccuracy float32 `json:"trackingAccuracy"`

	WebsockNotifConfig WebsockNotifConfig `json:"websockNotifConfig,omitempty"`
}
