/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// NotificationSubscriptionList - This type contains a list of subscriptions.
type NotificationSubscriptionList struct {

	ResourceURL LinkType `json:"resourceURL"`

	Subscription []Subscription `json:"subscription,omitempty"`
}
