/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api
// ConnectionType : This enumeration represents the connection type of an access point
type ConnectionType string

// List of ConnectionType
const (
	LTE ConnectionType = "LTE"
	WIFI ConnectionType = "Wifi"
	WIMAX ConnectionType = "Wimax"
	_5_G_NR ConnectionType = "5G NR"
	UNKNOWN ConnectionType = "UNKNOWN"
)
