/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type AreaInfo struct {

	// Shall include one point if the shape is CIRCLE. Shall include 3-15 points if the shape is POLYGON.
	Points []Point `json:"points"`

	// Shall be present if the shape is CIRCLE.
	Radius int32 `json:"radius,omitempty"`

	// The shape of the area monitored: 1 = CIRCLE. 2 = POLYGON
	Shape int32 `json:"shape"`
}
