/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserDistanceNotification struct {

	Links Links `json:"_links"`

	DistanceEvent DistanceCriteria `json:"distanceEvent"`

	MonitoredUsers UserList `json:"monitoredUsers"`

	// Shall be set to \"UserDistanceNotification\".
	NotificationType string `json:"notificationType"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`
}
