/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// Links - Hyperlink related to the resource. This shall be only included in the HTTP responses and in HTTP PUT requests.
type Links struct {

	Self LinkType `json:"self"`
}
