/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// TerminalLocation - A type containing device address, retrieval status and location information.
type TerminalLocation struct {

	// Address of the terminal to which the location information applies (e.g., 'sip' URI, 'tel' URI, 'acr' URI).
	Address string `json:"address"`

	CurrentLocation LocationInfo `json:"currentLocation,omitempty"`

	ErrorInformation ServiceError `json:"errorInformation,omitempty"`

	LocationRetrievalStatus RetrievalStatus `json:"locationRetrievalStatus"`
}
