/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type ZoneLocationEventNotification struct {

	Links Links `json:"_links"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address"`

	// Shall be set to \"ZoneLocationEventNotification\".
	NotificationType string `json:"notificationType"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	UserLocationEvent LocationEventType `json:"userLocationEvent"`

	// The identity of the zone. 
	ZoneId string `json:"zoneId"`
}
