/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserAreaSubscription struct {

	Links Links `json:"_links,omitempty"`

	// List of the users to be monitored. 
	AddressList []string `json:"addressList"`

	AreaDefine AreaInfo `json:"areaDefine"`

	// URI exposed by the client on which to receive notifications via HTTP. See note 1.
	CallbackReference string `json:"callbackReference,omitempty"`

	// A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server. See note 2.
	ClientCorrelator string `json:"clientCorrelator,omitempty"`

	ExpiryDeadline TimeStamp `json:"expiryDeadline,omitempty"`

	// List of user event values to generate notifications for (these apply to address specified). 
	LocationEventCriteria []LocationEventType `json:"locationEventCriteria,omitempty"`

	ReportingCtrl ReportingCtrl `json:"reportingCtrl,omitempty"`

	// This IE shall be set to true if a location estimate is required for each event report.
	ReportingLocationReq bool `json:"reportingLocationReq,omitempty"`

	// Set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, as specified in ETSI GS MEC 009 [4], clause 6.12a.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	// Shall be set to \"UserAreaSubscription\".
	SubscriptionType string `json:"subscriptionType"`

	// Number of meters of acceptable error.
	TrackingAccuracy float32 `json:"trackingAccuracy"`

	WebsockNotifConfig WebsockNotifConfig `json:"websockNotifConfig,omitempty"`
}
