/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// ServiceError - Used to indicate a notification termination or cancellation.
type ServiceError struct {

	// Message identifier, either with prefix SVC or with prefix POL
	MessageId string `json:"messageId"`

	// Message text, with replacement variables marked with %n, where n is an index into the list of <variables> elements, starting at 1
	Text string `json:"text"`

	// Variables to substitute into text string
	Variables []string `json:"variables,omitempty"`
}
