/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api
// LocationEventType : This type represents specified event types for UE location report.
type LocationEventType string

// List of LocationEventType
const (
	ENTERING_AREA_EVENT LocationEventType = "ENTERING_AREA_EVENT"
	LEAVING_AREA_EVENT LocationEventType = "LEAVING_AREA_EVENT"
)
