/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// UserList - A type containing list of users.
type UserList struct {

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Collection of the zone information list.
	User []UserInfo `json:"user,omitempty"`
}
