/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

type UserAreaNotification struct {

	Links Links `json:"_links"`

	// Address of user (e.g. ‘sip’ URI, ‘tel’ URI, ‘acr’ URI).
	Address string `json:"address"`

	CivicInfo CivicAddress `json:"civicInfo,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Shall be set to \"UserAreaNotification\".
	NotificationType string `json:"notificationType"`

	RelativeLocationInfo RelativeLocationInfo `json:"relativeLocationInfo,omitempty"`

	TimeStamp TimeStamp `json:"timeStamp,omitempty"`

	UserLocationEvent LocationEventType `json:"userLocationEvent"`
}
