/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// AccessPointInfo - A type containing access point information.
type AccessPointInfo struct {

	// Identifier of access point.
	AccessPointId string `json:"accessPointId"`

	ConnectionType ConnectionType `json:"connectionType"`

	// Interest realm of access point.
	InterestRealm string `json:"interestRealm,omitempty"`

	LocationInfo LocationInfo `json:"locationInfo,omitempty"`

	// Number of users currently on the access point.
	NumberOfUsers int32 `json:"numberOfUsers"`

	OperationStatus OperationStatus `json:"operationStatus"`

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Time zone of access point.
	Timezone string `json:"timezone,omitempty"`
}
