/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// AccessPointList - A type containing list of access points.
type AccessPointList struct {

	// Collection of the access point information list.
	AccessPoint []AccessPointInfo `json:"accessPoint,omitempty"`

	// Self referring URL
	ResourceURL string `json:"resourceURL"`

	// Identifier of zone
	ZoneId string `json:"zoneId"`
}
