/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api
// OperationStatus : An enumeration defining the operations status of an access point.
type OperationStatus string

// List of OperationStatus
const (
	SERVICEABLE OperationStatus = "Serviceable"
	UNSERVICEABLE OperationStatus = "Unserviceable"
	UNKNOWN OperationStatus = "Unknown"
)
