/*
 * ETSI GS MEC 013 - Location API
 *
 * The ETSI MEC ISG MEC013 Location API described using OpenAPI.
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location-api

// TerminalDistance - A type containing information about the distance from a terminal to a location or between two terminals, in addition the accuracy and a timestamp of the information are provided.
type TerminalDistance struct {

	// Accuracy of the provided distance in meters
	Accuracy int32 `json:"accuracy,omitempty"`

	// Distance from terminal to a location or between two terminals specified in meters
	Distance int32 `json:"distance"`

	Timestamp TimeStamp `json:"timestamp,omitempty"`
}
