definitions:
  domains.ZoneResponse:
    properties:
      id:
        type: string
      numAPs:
        type: integer
      numUnserviceableAPs:
        type: integer
      numUsers:
        type: integer
      resourceURL:
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /queries/zones:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get list of all zones
      tags:
      - Zones
  /queries/zones/{id}:
    get:
      consumes:
      - application/json
      description: Gets information about one specific zone identified by its ID
      parameters:
      - description: Zone ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.ZoneResponse'
        "404":
          description: Not Found
      summary: Gets information about one specific zone
      tags:
      - zones
swagger: "2.0"
